name: Compile and Execute

on:
    push:
        branches:
            - main

jobs:
  build-and-execute:
    runs-on: macos-15
    defaults:
      run:
        shell: bash
    env:
      ARCH: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create and switch to new branch
        run: |
          git checkout -b exec-build
          git push https://<PAT>@github.com/JEMcats-Software/LocalSpeech.git exec-build

      - name: Clone sherpa-onnx repository
        run: git clone https://github.com/k2-fsa/sherpa-onnx

      - name: Build sherpa-onnx
        run: |
          cd sherpa-onnx
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j6

      - name: Move sherpa-onnx-offline-tts to dev branch
        run: |
          git fetch origin dev
          git checkout dev
          mkdir -p download_data
          cp sherpa-onnx/bin/sherpa-onnx-offline-tts download_data/mac_exec
          git add download_data/mac_exec
          git commit -m "Update mac_exec with latest sherpa-onnx-offline-tts"
          git push https://<PAT>@github.com/JEMcats-Software/LocalSpeech.git dev

      - name: Remove exec-build branch
        run: |
          git branch -D exec-build
          git push https://<PAT>@github.com/JEMcats-Software/LocalSpeech.git --delete exec-build